version: "3.9"

services:
  app:
    build: .
    container_name: devops-node-app
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo 

  mongo:
    image: mongo:latest
    container_name: mongodb-service
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
