name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Node Setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install deps
      - name: Install dependencies
        run: npm install

      # 4️⃣ Docker Login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t umairaslam2/devops-node-app:${{ github.sha }} .
          docker tag umairaslam2/devops-node-app:${{ github.sha }} umairaslam2/devops-node-app:latest

      # 6️⃣ Trivy Security Scan (BLOCK ON HIGH/CRITICAL)
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: umairaslam2/devops-node-app:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table

      # 7️⃣ Push Docker Image
      - name: Push Docker Image
        run: |
          docker push umairaslam2/devops-node-app:${{ github.sha }}
          docker push umairaslam2/devops-node-app:latest

      # 8️⃣ Deploy to Kubernetes (later)
      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f .devops/k8s/
